
package ec.edu.espe.code.view;

/**
 *
 * @author Alex Trejo, PACSTORE, DCCO-ESPE
 */
public class FrmTaxCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TaxCalculator
     */
    public FrmTaxCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTaxCalculator = new javax.swing.JLabel();
        jlbhw21Singleton = new javax.swing.JLabel();
        jlblAlexTrejo = new javax.swing.JLabel();
        mbCalculator = new javax.swing.JMenuBar();
        mnState = new javax.swing.JMenu();
        mniUtah = new javax.swing.JMenuItem();
        mniCalifornia = new javax.swing.JMenuItem();
        mniArizona = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TaxCalculator");

        jlblTaxCalculator.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        jlblTaxCalculator.setText("Tax Calculator");

        jlbhw21Singleton.setText("hw21-Singleton");

        jlblAlexTrejo.setText("Alex Trejo");

        mnState.setText("State");

        mniUtah.setText("Utah");
        mniUtah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUtahActionPerformed(evt);
            }
        });
        mnState.add(mniUtah);

        mniCalifornia.setText("California");
        mniCalifornia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCaliforniaActionPerformed(evt);
            }
        });
        mnState.add(mniCalifornia);

        mniArizona.setText("Arizona");
        mniArizona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniArizonaActionPerformed(evt);
            }
        });
        mnState.add(mniArizona);

        mbCalculator.add(mnState);

        setJMenuBar(mbCalculator);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlblAlexTrejo)
                        .addGap(83, 83, 83)
                        .addComponent(jlbhw21Singleton)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlblTaxCalculator)
                        .addGap(117, 117, 117))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jlblTaxCalculator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbhw21Singleton)
                    .addComponent(jlblAlexTrejo))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniUtahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUtahActionPerformed
        // TODO add your handling code here:
        
        FrmUtah frmUtah= new FrmUtah();
        this.setVisible(false);
        
        frmUtah.setVisible(true);
        
    }//GEN-LAST:event_mniUtahActionPerformed

    private void mniArizonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniArizonaActionPerformed
        // TODO add your handling code here:
        FrmArizona frmArizona= new FrmArizona();
        this.setVisible(false);
        frmArizona.setVisible(true);
        
    }//GEN-LAST:event_mniArizonaActionPerformed

    private void mniCaliforniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCaliforniaActionPerformed
        // TODO add your handling code here:
        
        FrmCalifornia frmArizona= new FrmCalifornia();
        this.setVisible(false);
        frmArizona.setVisible(true);
    }//GEN-LAST:event_mniCaliforniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTaxCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTaxCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbhw21Singleton;
    private javax.swing.JLabel jlblAlexTrejo;
    private javax.swing.JLabel jlblTaxCalculator;
    private javax.swing.JMenuBar mbCalculator;
    private javax.swing.JMenu mnState;
    private javax.swing.JMenuItem mniArizona;
    private javax.swing.JMenuItem mniCalifornia;
    private javax.swing.JMenuItem mniUtah;
    // End of variables declaration//GEN-END:variables
}
