package ec.edu.espe.ehamanagement.view;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mongodb.client.MongoCollection;
import ec.edu.espe.EHAManagement.view.PnlReportGeneral;
import ec.edu.espe.ehamanagement.controller.Agenda;
import ec.edu.espe.ehamanagement.controller.FrmPrintGeneralReportController;
import ec.edu.espe.ehamanagement.controller.Inventory;
import utils.MongoConnection;
import ec.edu.espe.ehamanagement.model.Order;
import ec.edu.espe.ehamanagement.model.Product;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author NicolayChillo Gaman GeekLords at DCOO-ESPE
 */
public class FrmPrintGeneralReport extends javax.swing.JFrame {
    private final MongoConnection mongoConnection;
    private final MongoCollection ordersCollection;
    private final MongoCollection reportsCollection;
    private final MongoCollection productsCollection;
    private final  ArrayList <Order> readedOrders ;
    private final  ArrayList <Product> readedProducts ;
    /**
     * Creates new form FrmPrintGeneralReport
     */
    public FrmPrintGeneralReport(){
        mongoConnection = MongoConnection.getInstance();
        productsCollection = mongoConnection.getCollection("Products");
        ordersCollection = mongoConnection.getCollection("Orders");
        reportsCollection = mongoConnection.getCollection("Reports");
        readedOrders = Agenda.readAgenda(ordersCollection);
        readedProducts = Inventory.readInventory(productsCollection);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrintGeneralReport1 = new ec.edu.espe.EHAManagement.view.PnlReportGeneral();
        jPanel1 = new javax.swing.JPanel();
        BtnBack = new javax.swing.JButton();
        BtnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnPrint.setText("Print");
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(BtnBack)
                .addGap(107, 107, 107)
                .addComponent(BtnPrint)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(BtnPrint))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrintGeneralReport1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlPrintGeneralReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        FrmPrintGeneralReportController.insertReport(this);
        FrmPrintGeneralReportController.printReport(this);
    }//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        FrmPrincipalMenuBar open = new FrmPrincipalMenuBar();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrintGeneralReport().setVisible(true);
            }
        });
    }

    public MongoConnection getMongoConnection() {
        return mongoConnection;
    }

    public MongoCollection getOrdersCollection() {
        return ordersCollection;
    }

    public MongoCollection getReportsCollection() {
        return reportsCollection;
    }

    public MongoCollection getProductsCollection() {
        return productsCollection;
    }

    public ArrayList<Order> getReadedOrders() {
        return readedOrders;
    }

    public ArrayList<Product> getReadedProducts() {
        return readedProducts;
    }

    public JButton getBtnBack() {
        return BtnBack;
    }

    public JButton getBtnPrint() {
        return BtnPrint;
    }

    public PnlReportGeneral getPnlPrintGeneralReport1() {
        return pnlPrintGeneralReport1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnPrint;
    private javax.swing.JPanel jPanel1;
    private ec.edu.espe.EHAManagement.view.PnlReportGeneral pnlPrintGeneralReport1;
    // End of variables declaration//GEN-END:variables
}
