package ec.edu.espe.fashionstore.view;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan Jaguaco, Pythons, DCCO-ESPE
 */
public class FormOrder extends javax.swing.JFrame {

    DB db;
    DBCollection tabla;
    DBCursor cursor = null;
    BasicDBObject document = new BasicDBObject();
    
    public FormOrder() {
        try {
            Mongo mongo = new Mongo("localhost", 27017);
            db=mongo.getDB("FashionStore");
            tabla = db.getCollection("User");
            
        } catch (UnknownHostException e) {
            System.out.println("Error");
        }
        initComponents();
    }
    public void toList() throws UnknownHostException{
        tabla = db.getCollection("User");
        cursor = tabla.find();
        
        String [] columnNames = {"Name","Telephone","Direction"};
        DefaultTableModel model = new DefaultTableModel(columnNames,0);
        
        while(cursor.hasNext()){
            DBObject obj = cursor.next();
            String name = (String)obj.get("Name");
            String telephone = (String)obj.get("Telephone");
            String direction = (String)obj.get("Direction");
            model.addRow(new Object[]{name, telephone, direction});
            
        }
        //table.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnlimputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tlftext = new javax.swing.JTextField();
        cmbYear = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbDay = new javax.swing.JComboBox<>();
        pnldate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlButtoms = new javax.swing.JPanel();
        btmgenerate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btmContinue = new javax.swing.JButton();
        btmDelete = new javax.swing.JButton();
        directiontxt = new javax.swing.JTextField();
        btnfind = new javax.swing.JButton();
        btneliminate = new javax.swing.JButton();
        btnmodified = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlimputs.setBackground(new java.awt.Color(255, 255, 255));
        pnlimputs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel1.setText("Number Order:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        txtname.setToolTipText("Insert your full name");
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Telephone:");

        tlftext.setToolTipText("Insert your phone number");
        tlftext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlftextActionPerformed(evt);
            }
        });
        tlftext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tlftextKeyTyped(evt);
            }
        });

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2023", "2024" }));
        cmbYear.setToolTipText("Year");
        cmbYear.setBorder(null);

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbMonth.setToolTipText("Month");
        cmbMonth.setBorder(null);

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDay.setToolTipText("Day");
        cmbDay.setBorder(null);

        pnldate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnldate.setText("Date of Delivery");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Neighborhood:");

        pnlButtoms.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlButtomsLayout = new javax.swing.GroupLayout(pnlButtoms);
        pnlButtoms.setLayout(pnlButtomsLayout);
        pnlButtomsLayout.setHorizontalGroup(
            pnlButtomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        pnlButtomsLayout.setVerticalGroup(
            pnlButtomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        btmgenerate.setText("Generate a Order");
        btmgenerate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btmgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmgenerateActionPerformed(evt);
            }
        });

        jLabel6.setText("4747");
        jLabel6.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel6ComponentAdded(evt);
            }
        });

        btmContinue.setBackground(new java.awt.Color(51, 255, 51));
        btmContinue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btmContinue.setText("Continue");
        btmContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmContinueMouseClicked(evt);
            }
        });
        btmContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmContinueActionPerformed(evt);
            }
        });

        btmDelete.setBackground(new java.awt.Color(255, 0, 0));
        btmDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btmDelete.setForeground(new java.awt.Color(255, 255, 255));
        btmDelete.setText("Exit");
        btmDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmDeleteMouseClicked(evt);
            }
        });

        directiontxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directiontxtActionPerformed(evt);
            }
        });
        directiontxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                directiontxtKeyTyped(evt);
            }
        });

        btnfind.setText("Find");
        btnfind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfindMouseClicked(evt);
            }
        });
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        btneliminate.setText("Eliminate");
        btneliminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminateActionPerformed(evt);
            }
        });

        btnmodified.setText("Modified");
        btnmodified.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifiedActionPerformed(evt);
            }
        });

        jLabel7.setText("Options");

        javax.swing.GroupLayout pnlimputsLayout = new javax.swing.GroupLayout(pnlimputs);
        pnlimputs.setLayout(pnlimputsLayout);
        pnlimputsLayout.setHorizontalGroup(
            pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlButtoms, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlimputsLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(btmgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlimputsLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btmContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlimputsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlimputsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlimputsLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlimputsLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(17, 17, 17))))
                    .addGroup(pnlimputsLayout.createSequentialGroup()
                        .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(directiontxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tlftext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btneliminate)
                            .addComponent(btnmodified)
                            .addComponent(btnfind))
                        .addGap(1, 1, 1))
                    .addGroup(pnlimputsLayout.createSequentialGroup()
                        .addComponent(pnldate)
                        .addGap(37, 37, 37)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        pnlimputsLayout.setVerticalGroup(
            pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlimputsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btmgenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfind))
                .addGap(18, 18, 18)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tlftext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodified))
                .addGap(35, 35, 35)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(directiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminate))
                .addGap(33, 33, 33)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnldate)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlimputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmContinue)
                    .addComponent(btmDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(pnlButtoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlimputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlimputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmContinueActionPerformed
       
        if(txtname.getText().equals("") || (tlftext.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Complete all the remaining fields");
        }else{
            document.put("Name","'"+txtname.getText() + "'" );
            document.put("Telephone", tlftext.getText());
            document.put("Direction", directiontxt.getText());
            document.put("Year", cmbYear.getSelectedItem());
            document.put("Month", cmbMonth.getSelectedItem());
            document.put("Day", cmbDay.getSelectedItem());
            tabla.insert(document);
        }
        
    }//GEN-LAST:event_btmContinueActionPerformed

    private void tlftextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlftextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlftextActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        //deberia validar los datos 
        // la tarea es hacer que no se ingresen caracteres especiales solo nombres 
        //usar JOptionPane.showMessageDialog(this,"mensaje de que ingrse correctamente los datos);
        //Borrar toda esa cadena que habia puesto el usuario
        //mandarle hacia donde esta errado automaticamente
        //usar los diferentes comando del .show
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z') &&  (c<'A' || c>'Z')) evt.consume();
        
        
    }//GEN-LAST:event_txtnameKeyTyped

    private void tlftextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlftextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_tlftextKeyTyped

    private void btmgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmgenerateActionPerformed
        // TODO add your handling code here:
        int number = 12;
        JOptionPane.showMessageDialog(this, "The Number of the Order is generate");
        
    }//GEN-LAST:event_btmgenerateActionPerformed

    private void jLabel6ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel6ComponentAdded

    }//GEN-LAST:event_jLabel6ComponentAdded

    private void btmContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmContinueMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btmContinueMouseClicked

    private void btmDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmDeleteMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btmDeleteMouseClicked

    private void directiontxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directiontxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directiontxtActionPerformed

    private void directiontxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_directiontxtKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'a' || c>'z') &&  (c<'A' || c>'Z')) evt.consume();
    }//GEN-LAST:event_directiontxtKeyTyped

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
        // TODO add your handling code here:  
        document.put("Name", txtname.getText());
        cursor = tabla.find(document);
        
        while(cursor.hasNext()){
            DBObject obj = cursor.next();
            String name = (String)obj.get("Name");
            String telephone = (String)obj.get("Telephone");
            String neighborhood = (String)obj.get("Neighborhood");
            
            txtname.setText(name);
            tlftext.setText(telephone);
            directiontxt.setText(neighborhood);
            System.out.println(name + telephone + neighborhood);
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void btnfindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfindMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnfindMouseClicked

    private void btnmodifiedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifiedActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Complete the name");
        }else
        {
          document.put("Name", txtname.getText());
          BasicDBObject documentnew = new BasicDBObject();
          documentnew.put("Name","'"+txtname.getText() + "'" );
          documentnew.put("Telephone", tlftext.getText());
          documentnew.put("Direction", directiontxt.getText());
          documentnew.put("Year", cmbYear.getSelectedItem());
          documentnew.put("Month", cmbMonth.getSelectedItem());
          documentnew.put("Day", cmbDay.getSelectedItem());
          tabla.findAndModify(document, documentnew);
        }
    }//GEN-LAST:event_btnmodifiedActionPerformed

    private void btneliminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminateActionPerformed
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Complete the name to find");
        }else
        {
            document.put("Name",txtname.getText());
            tabla.remove(document);
        }
    }//GEN-LAST:event_btneliminateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormOrder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmContinue;
    private javax.swing.JButton btmDelete;
    private javax.swing.JButton btmgenerate;
    private javax.swing.JButton btneliminate;
    private javax.swing.JButton btnfind;
    private javax.swing.JButton btnmodified;
    private javax.swing.JComboBox<String> cmbDay;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JTextField directiontxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlButtoms;
    private javax.swing.JLabel pnldate;
    private javax.swing.JPanel pnlimputs;
    private javax.swing.JTextField tlftext;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
