package ec.edu.espe.inclass.view;

import ec.edu.espe.inclass.controller.CourseController;
import ec.edu.espe.inclass.controller.StudentController;
import ec.edu.espe.inclass.controller.TeacherController;
import ec.edu.espe.inclass.controller.TutorshipController;
import ec.edu.espe.inclass.model.Course;
import ec.edu.espe.inclass.model.Student;
import ec.edu.espe.inclass.model.Teacher;
import ec.edu.espe.inclass.model.Tutorship;
import static ec.edu.espe.inclass.view.InClass.dBManager;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import utils.DBManager;

/**
 *
 * @author Stephen Drouet, Developer Bears, DCC-ESPE
 */
public class FrmStudents extends javax.swing.JFrame {

    /**
     * Creates new form frmAddStudent
     */
    
    static Teacher teacher;
    static DBManager dBManager;
    
    public FrmStudents() {
        initComponents();                
        
        refreshTable();
        
    }
    
    public final void refreshTable() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("#");
        model.addColumn("Name");
        model.addColumn("ESPE ID");                
        
        int i = 1;
        for (Student student : teacher.getCourses().get(0).getStudents()) {
            
            model.addRow(new Object[]{i,student.getName(), student.getEspeId()});
            i++;
        }                                
                
        tblStudents.setModel(model);
    }
    
    public void addStudentGui(String name, String id) {
        Student student;
        student = teacher.getCourses().get(0).addStudent(name, id);
        //dBManager.createDocument("Students", StudentController.studentToJsonForDB(student, teacher.getCourses().get(0).getNrc()));
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblTypeUser = new javax.swing.JLabel();
        btnStudents = new javax.swing.JLabel();
        btnAttendance = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNrc = new javax.swing.JLabel();
        lblCourseName1 = new javax.swing.JLabel();
        lblImgCourse = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnAddStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 140, 74));

        lblUser.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Santiago");

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_64_bl.png"))); // NOI18N
        btnHome.setBorder(null);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_64_bl_br.png"))); // NOI18N

        lblTypeUser.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        lblTypeUser.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeUser.setText("profesor");

        btnStudents.setBackground(new java.awt.Color(42, 140, 74));
        btnStudents.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStudents.setText("Students");
        btnStudents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStudents.setOpaque(true);
        btnStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentsMouseExited(evt);
            }
        });

        btnAttendance.setBackground(new java.awt.Color(42, 140, 74));
        btnAttendance.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAttendance.setText("Attendance");
        btnAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAttendance.setOpaque(true);
        btnAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAttendanceMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnStudents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTypeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
            .addComponent(btnAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHome)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTypeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(36, 36, 36)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        jPanel3.setBackground(new java.awt.Color(100, 194, 123));

        lblNrc.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        lblNrc.setForeground(new java.awt.Color(255, 255, 255));
        lblNrc.setText("1010");

        lblCourseName1.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        lblCourseName1.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseName1.setText("Object Oriented Programming");

        lblImgCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aula_100_bl.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblImgCourse)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseName1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addComponent(lblNrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblImgCourse)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNrc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 790, 140));

        tblStudents.setBackground(new java.awt.Color(255, 255, 255));
        tblStudents.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        tblStudents.setForeground(new java.awt.Color(0, 0, 0));
        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Students", "ESPE ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudents.setGridColor(new java.awt.Color(102, 102, 102));
        tblStudents.setOpaque(false);
        tblStudents.setRowHeight(30);
        tblStudents.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblStudents);
        if (tblStudents.getColumnModel().getColumnCount() > 0) {
            tblStudents.getColumnModel().getColumn(0).setResizable(false);
            tblStudents.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblStudents.getColumnModel().getColumn(1).setResizable(false);
            tblStudents.getColumnModel().getColumn(2).setResizable(false);
            tblStudents.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 450, 460));

        btnAddStudent.setBackground(new java.awt.Color(42, 140, 74));
        btnAddStudent.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddStudent.setText("+ Add student");
        btnAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddStudent.setOpaque(true);
        btnAddStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStudentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddStudentMouseExited(evt);
            }
        });
        jPanel1.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseEntered
        btnStudents.setBackground(new Color(100, 194, 123));
    }//GEN-LAST:event_btnStudentsMouseEntered

    private void btnStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseExited
        btnStudents.setBackground(new Color(42, 140, 74));
    }//GEN-LAST:event_btnStudentsMouseExited

    private void btnAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttendanceMouseEntered
        btnAttendance.setBackground(new Color(100, 194, 123));
    }//GEN-LAST:event_btnAttendanceMouseEntered

    private void btnAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAttendanceMouseExited
        btnAttendance.setBackground(new Color(42, 140, 74));
    }//GEN-LAST:event_btnAttendanceMouseExited

    private void btnAddStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentMouseEntered
        btnAddStudent.setBackground(new Color(100, 194, 123));
    }//GEN-LAST:event_btnAddStudentMouseEntered

    private void btnAddStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentMouseExited
        btnAddStudent.setBackground(new Color(42, 140, 74));
    }//GEN-LAST:event_btnAddStudentMouseExited

    private void btnAddStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStudentMouseClicked
        FrmAddStudent frmAddStudent;
        frmAddStudent = new FrmAddStudent(this);
        frmAddStudent.setVisible(true);
    }//GEN-LAST:event_btnAddStudentMouseClicked

    public static void connectMongoDB() {
        ArrayList<Tutorship> tutorships;
        ArrayList<Course> courses;
        ArrayList<Student> students;

        dBManager = new DBManager();
        dBManager.connect("mongodb+srv://oop22:oop22@cluster0.cd2tjad.mongodb.net/test", "InClassProject");
        teacher = new Teacher();
        teacher = TeacherController.jsonToTeacher((String) dBManager.readCollection("Teacher").get(0));
        tutorships = TutorshipController.loadTutorships(dBManager.readCollection("Tutorships"));
        courses = CourseController.loadCourses(dBManager.readCollection("Courses"));

        for (Course course : courses) {
            students = StudentController.loadStudents(dBManager.readCollection("Students", "nrc", course.getNrc()));
            course.setStudents(students);
        }

        teacher.setTutorships(tutorships);
        teacher.setCourses(courses);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        connectMongoDB();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddStudent;
    private javax.swing.JLabel btnAttendance;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel btnStudents;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourseName1;
    private javax.swing.JLabel lblImgCourse;
    private javax.swing.JLabel lblNrc;
    private javax.swing.JLabel lblTypeUser;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
