/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.system.view;

/**
 *
 * @author Reishel Tipan, PACSTORE, DCCO-ESPE
 */
public class RegistrationSystem extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationSystem
     */
    public RegistrationSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuHEMSystem = new javax.swing.JMenu();
        imtAbout = new javax.swing.JMenuItem();
        itmQuit = new javax.swing.JMenuItem();
        mnuProduct = new javax.swing.JMenu();
        itmAddProduct = new javax.swing.JMenuItem();
        itmUpdateProduct = new javax.swing.JMenuItem();
        itmDeleteProduct = new javax.swing.JMenuItem();
        mnuFindProduct = new javax.swing.JMenu();
        itmById = new javax.swing.JMenuItem();
        itmByName = new javax.swing.JMenuItem();
        mnuView = new javax.swing.JMenu();
        itmInventory = new javax.swing.JMenuItem();
        itmSales = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        itmReportIssues = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Huerto EcoMarket");

        jLabel1.setText("Huerto EcoMarket System");

        mnuHEMSystem.setText("HEMSystem");

        imtAbout.setText("About");
        imtAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imtAboutActionPerformed(evt);
            }
        });
        mnuHEMSystem.add(imtAbout);

        itmQuit.setText("Quit");
        mnuHEMSystem.add(itmQuit);

        jMenuBar1.add(mnuHEMSystem);

        mnuProduct.setText("Product");

        itmAddProduct.setText("Add Product");
        mnuProduct.add(itmAddProduct);

        itmUpdateProduct.setText("Update Product");
        mnuProduct.add(itmUpdateProduct);

        itmDeleteProduct.setText("Delete Product");
        mnuProduct.add(itmDeleteProduct);

        mnuFindProduct.setText("Find Product");

        itmById.setText("By Id");
        mnuFindProduct.add(itmById);

        itmByName.setText("By Name");
        mnuFindProduct.add(itmByName);

        mnuProduct.add(mnuFindProduct);

        jMenuBar1.add(mnuProduct);

        mnuView.setText("View");

        itmInventory.setText("Inventory");
        mnuView.add(itmInventory);

        itmSales.setText("Sales");
        mnuView.add(itmSales);

        jMenuBar1.add(mnuView);

        mnuHelp.setText("Help");

        itmReportIssues.setText("Report issues");
        mnuHelp.add(itmReportIssues);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imtAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imtAboutActionPerformed
        FrmAbout frmAbout;
        frmAbout= new FrmAbout();
        frmAbout.setVisible(true);
    }//GEN-LAST:event_imtAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imtAbout;
    private javax.swing.JMenuItem itmAddProduct;
    private javax.swing.JMenuItem itmById;
    private javax.swing.JMenuItem itmByName;
    private javax.swing.JMenuItem itmDeleteProduct;
    private javax.swing.JMenuItem itmInventory;
    private javax.swing.JMenuItem itmQuit;
    private javax.swing.JMenuItem itmReportIssues;
    private javax.swing.JMenuItem itmSales;
    private javax.swing.JMenuItem itmUpdateProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuFindProduct;
    private javax.swing.JMenu mnuHEMSystem;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuProduct;
    private javax.swing.JMenu mnuView;
    // End of variables declaration//GEN-END:variables
}
